export * from "./Auth";
export * from "./Home";
export * from "./NotFound";
export * from "./Learning";
export * from "./Profile";
export * from "./Feedback";
export * from "./Search";
export * from "./Admin";
export * from "./Contact";
export * from "./Forum";
export * from "./StudyMaterial"
export * from "./Payment"